/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author uribe.markel
 */
import java.util.Random;
public class JFrameBerria extends javax.swing.JFrame {

    /**
     * Creates new form JFrameBerria
     */
    public JFrameBerria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TextIzendatzailea2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TextIzendatzailea1 = new javax.swing.JTextField();
        TextZenbakitzailea1 = new javax.swing.JTextField();
        TextZenbakitzailea2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextHamartar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        zenba1 = new javax.swing.JTextField();
        izenda1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        zenba2 = new javax.swing.JTextField();
        izenda2 = new javax.swing.JTextField();
        zuzendu = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        zenba3 = new javax.swing.JTextField();
        izenda3 = new javax.swing.JTextField();
        berriak = new javax.swing.JButton();
        erantzuna = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("ZATIKIAK SIMPLIFIKATU");

        TextZenbakitzailea1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextZenbakitzailea1ActionPerformed(evt);
            }
        });

        TextZenbakitzailea2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextZenbakitzailea2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Hamartarrean:");

        jButton1.setText("=");
        jButton1.setToolTipText("");
        jButton1.setActionCommand("botoia");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextHamartar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TextZenbakitzailea1)
                                .addComponent(TextIzendatzailea1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(12, 12, 12)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TextIzendatzailea2)
                                .addComponent(TextZenbakitzailea2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextZenbakitzailea2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jButton1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextIzendatzailea2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TextZenbakitzailea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextIzendatzailea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextHamartar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("BATUKETA ASMATU");

        zenba1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zenba1ActionPerformed(evt);
            }
        });

        izenda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izenda1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setText("+");

        zenba2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zenba2ActionPerformed(evt);
            }
        });

        zuzendu.setText("zuzendu");
        zuzendu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zuzenduActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setText("=");

        zenba3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zenba3ActionPerformed(evt);
            }
        });

        berriak.setText("Zenbaki berriak");
        berriak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                berriakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(zenba1)
                                    .addComponent(izenda1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(zenba2)
                                    .addComponent(izenda2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5))
                            .addComponent(berriak))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(zuzendu)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(zenba3)
                                .addComponent(izenda3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(erantzuna, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(zenba3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(izenda3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zenba1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zenba2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(izenda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(izenda2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(berriak)
                    .addComponent(zuzendu))
                .addGap(18, 18, 18)
                .addComponent(erantzuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextZenbakitzailea1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextZenbakitzailea1ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_TextZenbakitzailea1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Zatikia zat = new Zatikia(Integer.parseInt(TextZenbakitzailea1.getText()), Integer.parseInt(TextIzendatzailea1.getText()));
        
        zat.sinplifikatu();
        
        TextZenbakitzailea2.setText(""+zat.getZenbakitzailea());
        TextIzendatzailea2.setText(""+zat.getIzendatzailea());
        jTextHamartar.setText(""+String.format("%.2f", Zatikia.hamartarBaliokidea(zat)));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TextZenbakitzailea2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextZenbakitzailea2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextZenbakitzailea2ActionPerformed

    private void izenda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izenda1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_izenda1ActionPerformed

    private void zenba2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zenba2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zenba2ActionPerformed

    private void zenba1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zenba1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zenba1ActionPerformed

    private void zuzenduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zuzenduActionPerformed
        Zatikia zat1 = new Zatikia(Integer.parseInt(zenba1.getText()), Integer.parseInt(izenda1.getText()));
        Zatikia zat2 = new Zatikia(Integer.parseInt(zenba2.getText()), Integer.parseInt(izenda2.getText()));
        
        Zatikia batu = new Zatikia(Integer.parseInt(zenba3.getText()), Integer.parseInt(izenda3.getText()));
        if(Zatikia.isSameaAs(Zatikia.batu(zat1, zat2).sinplifikatu(), batu) == true){
            erantzuna.setText("Erantzuna zuzena da!!");
        }else{
            erantzuna.setText("Erantzuna okerra da!!");
        }
        System.out.println(Zatikia.batu(zat1, zat2).sinplifikatu());
        System.out.println(batu);
    }//GEN-LAST:event_zuzenduActionPerformed

    private void zenba3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zenba3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zenba3ActionPerformed

    private void berriakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_berriakActionPerformed
        Random rand = new Random();
        Zatikia zat1 = new Zatikia(rand.nextInt(20), rand.nextInt(20));
        Zatikia zat2 = new Zatikia(rand.nextInt(20), rand.nextInt(20));
        
        zenba1.setText(""+zat1.getZenbakitzailea());
        izenda1.setText(""+zat1.getIzendatzailea());
        
        zenba2.setText(""+zat2.getZenbakitzailea());
        izenda2.setText(""+zat2.getIzendatzailea());
        
        
    }//GEN-LAST:event_berriakActionPerformed

    
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameBerria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextIzendatzailea1;
    private javax.swing.JTextField TextIzendatzailea2;
    private javax.swing.JTextField TextZenbakitzailea1;
    private javax.swing.JTextField TextZenbakitzailea2;
    private javax.swing.JButton berriak;
    private javax.swing.JTextField erantzuna;
    private javax.swing.JTextField izenda1;
    private javax.swing.JTextField izenda2;
    private javax.swing.JTextField izenda3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextHamartar;
    private javax.swing.JTextField zenba1;
    private javax.swing.JTextField zenba2;
    private javax.swing.JTextField zenba3;
    private javax.swing.JButton zuzendu;
    // End of variables declaration//GEN-END:variables
}
